format_version: 2
pipelines:
  yamlpipe1:
    group: spring-boot-example
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/Knappek/spring-boot-hello-world-example.git
    stages:
      - build: # name of stage
          jobs:
            elastic_profile_id: "maven"
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: ls
